podTemplate(cloud:'openshift',label: 'docker',
  containers: [
    containerTemplate(
      name: 'jnlp',
      image: '192.168.1.202:5000/shubhamasati/donotcopy:jenkinsslave',
      //image: 'manya97/jenkins_tryout',
      alwaysPullImage: true,
      privileged: true,
      envVars: [envVar(key:'http_proxy',value:''),envVar(key:'https_proxy',value:'')],
      args: '${computer.jnlpmac} ${computer.name}',
      ttyEnabled: true
    )],
    volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')])
{
    node('docker')
    {
        container('jnlp')
        {
            sh 'docker pull busybox'
        }
    }
    
}    
